import Head from 'next/head';
import PropTypes from 'prop-types';
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title>{`Quiz Pekan 3 - ${metaTitle}`}</title>
        <meta name="description" content={metaDescription || "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </main>
    </>
  );
};

Layout.propTypes = {
  children: PropTypes.any,
  metaTitle: PropTypes.string,
  metaDescription: PropTypes.string,
};
